"""add all.

Revision ID: 43231b1a2b46
Revises: cd8a23b76f2b
Create Date: 2022-01-08 20:27:36.148370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43231b1a2b46'
down_revision = 'cd8a23b76f2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pictures', sa.Column('test_id', sa.Integer(), nullable=True))
    op.drop_constraint('fk_pictures_user_id_tests', 'pictures', type_='foreignkey')
    op.create_foreign_key(op.f('fk_pictures_test_id_tests'), 'pictures', 'tests', ['test_id'], ['id'])
    op.drop_column('pictures', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pictures', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_pictures_test_id_tests'), 'pictures', type_='foreignkey')
    op.create_foreign_key('fk_pictures_user_id_tests', 'pictures', 'tests', ['user_id'], ['id'])
    op.drop_column('pictures', 'test_id')
    # ### end Alembic commands ###
