"""add admin state

Revision ID: 7a274ba4bc82
Revises: 0e2ff406ce03
Create Date: 2022-01-12 00:37:08.383457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a274ba4bc82'
down_revision = '0e2ff406ce03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_login', sa.Column('state', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('main_login', 'state')
    # ### end Alembic commands ###
