"""add admin state

Revision ID: c1334b743bf5
Revises: 7a274ba4bc82
Create Date: 2022-01-12 01:03:33.971179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1334b743bf5'
down_revision = '7a274ba4bc82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('state', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'state')
    # ### end Alembic commands ###
